### ISSUE TITLE
Permissions and temp downloads folder

### ISSUE THREAD

**Issue by robflate** [RandomNinjaAtk/docker-amd#1] opened 2020-08-05 20:51 UTC
Thanks for the script. I've got it setup and it's downloading and sending Lidarr import notifications, however I don't think I have the `DOWNLOADS` env variable set correctly and I'm also having permissions issues.

When AMD first creates the downloads folder, it is owned by root and when tracks are downloaded, AMD reports in the log that the folder does not exist;

<img width="1008" alt="Screenshot 2020-08-05 at 21 12 41" src="https://user-images.githubusercontent.com/4172375/89459557-bc0ca900-d760-11ea-82c0-ca9fd60b010e.png">

**AMD Log**
```
1 of 46 :: Four Tet :: 4T Recordings :: SEARCHING...
1 of 46 :: Four Tet :: 4T Recordings :: DOWNLOADING :: https://www.deezer.com/album/132511572
mv: cannot stat '/home/user/Docker/media-server/data/direct/lidarr-amd/amd/dlclient/*': No such file or directory
chmod: cannot access '/home/user/Docker/media-server/data/direct/lidarr-amd/amd/import/Four Tet - 4T Recordings (WEB)-132511572-deemix/*': No such file or directory
1 of 46 :: Four Tet :: 4T Recordings :: LIDARR IMPORT NOTIFICATION SENT! :: /home/user/Docker/media-server/data/direct/lidarr-amd/amd/import/Four Tet - 4T Recordings (WEB)-132511572-deemix
```
**Lidarr Log**
`Folder/File specified for import scan [/home/user/Docker/media-server/data/direct/lidarr-amd/amd/import/Four Tet - 4T Recordings (WEB)-132511572-deemix] doesn't exist.`

**docker-compose.yml**
```
  lidarr-amd:
    image: randomninjaatk/amd:latest
    container_name: lidarr-amd
    restart: unless-stopped
    network_mode: service:pia-vpn
    depends_on:
      - pia-vpn
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/user/Docker/media-server/config/lidarr-amd:/config
      - /home/user/Docker/media-server/data/direct/lidarr-amd:/downloads
    environment:
      PUID: 501
      PGID: 999
      TZ: Europe/London
      DOWNLOADS: "/home/user/Docker/media-server/data/direct/lidarr-amd"
      AUTOSTART: "true"
      LidarrUrl: "http://lidarr:8686"
      LidarrAPIkey: "redacted"
      MBRAINZMIRROR: "https://musicbrainz.org"
      MBRATELIMIT: 1
      ARL_TOKEN: "redacted"
      quality: "FLAC"
      FolderPermissions: 766
      FilePermissions: 666
```
If I `CHOWN` the download folder with 501:999 the 2 files that show as `Binary` become folders but the same errors still occur.

Apologies if I'm doing something stupid but any help appreciated. Thanks.

**Comment by RandomNinjaAtk** [comment] 2020-08-06 00:29
I've been pushing lots of code updates as I continue to test. I think I may have already resolved some of this.... Be sure your on the latest image to get the latest script code

Another image should be be building now... Let me know once you've fully updated and run another test...

**Comment by robflate** [comment] 2020-08-06 08:32
I deleted the downloads folder and updated the image. What's the best way to know which version I'm on?

The downloads folder is created and is still owned by root. AMD logs show downloads and success and I can see download bandwidth being used but the files don't appear in the downloads folder. If I `CHOWN` the folder to match the `PUID` and `GUID` and run again, AMD downloads tracks but again they don't appear in the downloads folder.

```
1 of 46 :: Four Tet :: 2020 :: Single :: 4T Recordings :: SEARCHING...
1 of 46 :: Four Tet :: 2020 :: Single :: 4T Recordings :: ERROR :: Provided URL is broken, fallback to fuzzy search...
1 of 46 :: Four Tet :: 2020 :: Single :: 4T Recordings :: FUZZY SEARCHING...
1 of 46 :: Four Tet :: 2020 :: Single :: 4T Recordings :: DOWNLOADING :: 4T Recordings :: https://deezer.com/album/132511572...
INFO:deemix:Linux-5.4.0-42-generic-x86_64-with-glibc2.29 - Python 3.8.2, deemix 1.1.30
INFO:deemix:Generating queue item for: https://deezer.com/album/132511572
INFO:deemix:[track_882268522_9] Added to queue.
INFO:deemix:[track_882268522_9] Started downloading.
INFO:deemix:[Four Tet - 4T Recordings] Getting the tags
INFO:deemix:[Four Tet - 4T Recordings] Getting extra track infos
INFO:deemix:[Four Tet - 4T Recordings] Getting the album cover
INFO:deemix:[Four Tet - 4T Recordings] Downloading the track
INFO:deemix:[Four Tet - 4T Recordings] Applying tags to the track
INFO:deemix:[Four Tet - 4T Recordings] Track download completed
INFO:deemix:[track_882268522_9] Finished downloading.
All done!
```

**Comment by SebNYD** [comment] 2020-08-06 08:45
Hello,

I'm getting a similar issue although I can see the files that are being downloaded. All folders created by AMD are owned by root instead of the user defined by PUID & PGID.

As a result (I think), Lidarr can't see the files and no import occurs.

**Comment by RandomNinjaAtk** [comment] 2020-08-06 09:01
> I deleted the downloads folder and updated the image. What's the best way to know which version I'm on?
> 
> 
> 
> The downloads folder is created and is still owned by root. AMD logs show downloads and success and I can see download bandwidth being used but the files don't appear in the downloads folder. If I `CHOWN` the folder to match the `PUID` and `GUID` and run again, AMD downloads tracks but again they don't appear in the downloads folder.
> 
> 
> 
> ```
> 
> 1 of 46 :: Four Tet :: 2020 :: Single :: 4T Recordings :: SEARCHING...
> 
> 1 of 46 :: Four Tet :: 2020 :: Single :: 4T Recordings :: ERROR :: Provided URL is broken, fallback to fuzzy search...
> 
> 1 of 46 :: Four Tet :: 2020 :: Single :: 4T Recordings :: FUZZY SEARCHING...
> 
> 1 of 46 :: Four Tet :: 2020 :: Single :: 4T Recordings :: DOWNLOADING :: 4T Recordings :: https://deezer.com/album/132511572...
> 
> INFO:deemix:Linux-5.4.0-42-generic-x86_64-with-glibc2.29 - Python 3.8.2, deemix 1.1.30
> 
> INFO:deemix:Generating queue item for: https://deezer.com/album/132511572
> 
> INFO:deemix:[track_882268522_9] Added to queue.
> 
> INFO:deemix:[track_882268522_9] Started downloading.
> 
> INFO:deemix:[Four Tet - 4T Recordings] Getting the tags
> 
> INFO:deemix:[Four Tet - 4T Recordings] Getting extra track infos
> 
> INFO:deemix:[Four Tet - 4T Recordings] Getting the album cover
> 
> INFO:deemix:[Four Tet - 4T Recordings] Downloading the track
> 
> INFO:deemix:[Four Tet - 4T Recordings] Applying tags to the track
> 
> INFO:deemix:[Four Tet - 4T Recordings] Track download completed
> 
> INFO:deemix:[track_882268522_9] Finished downloading.
> 
> All done!
> 
> ```

Based on the config you provided earlier your problem is probably caused by having the download env variable incorrectly set. You need to set the variable to /downloads

Based on your provided config

**Comment by RandomNinjaAtk** [comment] 2020-08-06 09:04
> Hello,
> 
> 
> 
> I'm getting a similar issue although I can see the files that are being downloaded. All folders created by AMD are owned by root instead of the user defined by PUID & PGID.
> 
> 
> 
> As a result (I think), Lidarr can't see the files and no import occurs.
> 
> 
> 
> (I do have latest images of Lidarr and AMD)
> 
> 

If Lidarr is not importing it at all, you probably have a volume mapping issue and lidarr can't see the data. You can increase your lidarr logging to trace to see if lidarr is reporting any errors.

Make sure your volume for your downloads folder exists on your lidarr container or it won't work.

**Comment by robflate** [comment] 2020-08-06 10:10
> Based on the config you provided earlier your problem is probably caused by having the download env variable incorrectly set. You need to set the variable to /downloads

Thanks. The downloads now appear in the dlclient folder and are moved to the import folder, however, Lidarr logs show;

`Folder/File specified for import scan [/downloads/amd/import/Four Tet - Pink Remixes (2014)-WEB-EP-deemix] doesn't exist.`

- Lidarr volume: `- $DATA/direct/lidarr-amd:/downloads`
- AMD volume: `- $DATA/direct/lidarr-amd:/downloads`
- AMD DOWNLOADS env var: `"/downloads"`

Also, is it normal for the downloads folder to be owned by root or should the container apply permissions based on the PUID:GUID env vars like it does with the `/config` folder? Thanks again.

**Comment by RandomNinjaAtk** [comment] 2020-08-06 10:23
@robflate 

Since your mappings now look correct, in Lidarr, you probably should see if you can see the directories using the Manual Import. If you cannot see them, then the error would make sense.

Or from Lidarr's docker cli, run this command: `ls /downloads/amd/import` and see what data comes back..

**Comment by robflate** [comment] 2020-08-06 10:38
If I run `ls /downloads/amd/import` I can see `Four Tet - Pink Remixes (2014)-WEB-EP-deemix` and the files inside.

If I try to add `/downloads` as a root folder in Lidarr I get `-- Folder is not writable by user abc`

Both Lidarr and AMD have the following env vars;

```
PUID: 501
PGID: 999
```

**Comment by RandomNinjaAtk** [comment] 2020-08-06 10:45
This will probably fix it: https://github.com/RandomNinjaAtk/docker-amd/commit/2f6e4b9a2b0402c778bf670b66b0152559193ad8

Check for image updates soon, it should be building now.... I mostly use Unraid and I haven't seen an issue, but this should be resolved with this change... I think....

**Comment by robflate** [comment] 2020-08-06 11:28
Pulled the latest image and permissions are set so the root of `/downloads` is owned by `root:root` and everything under it is now owned by `PUID:GUID`. However Lidarr still says;

`Folder/File specified for import scan [/downloads/amd/import/Four Tet - Pink Remixes (2014)-WEB-EP-deemix] doesn't exist.`

trying to manually import shows;

`Invalid request Validation failed: -- Folder is not writable by user abc`

I also tried `FolderPermissions: 777` and those permissions were applied but I still get the above error.

**Comment by SebNYD** [comment] 2020-08-06 11:31
Hello,

On my end (I'm on a Synology), the latest image did the trick, Lidarr is now importing successfully.

Thanks a lot !

**Comment by RandomNinjaAtk** [comment] 2020-08-06 11:34
> 
> 
> Pulled the latest image and permissions are set so the root of `/downloads` is owned by `root:root` and everything under it is now owned by `PUID:GUID`. However Lidarr still says;
> 
> `Folder/File specified for import scan [/downloads/amd/import/Four Tet - Pink Remixes (2014)-WEB-EP-deemix] doesn't exist.`
> 
> trying to manually import shows;
> 
> `Invalid request Validation failed: -- Folder is not writable by user abc`
> 
> I also tried `FolderPermissions: 777` and those permissions were applied but I still get the above error.

What version number is your script? Should be at the top of the log. If you open download.bash you should see all the new chown commands, so this should be fully resolved, just like @sebnyd stated...

**Comment by robflate** [comment] 2020-08-06 12:29
`SCRIPT VERSION 1.0.01` when I made my previous post.

What I think got it all working was I changed the volume mappings and the AMD `DOWNLOAD` env var;

Old volume mapping: `- $DATA/direct/lidarr-amd:/downloads`
New volume mapping: `- $DATA:/data`

Old DOWNLOAD var: `/downloads`
New DOWNLOAD var: `/data/direct/lidarr-amd`

Old and new all point to the same place `/data/direct/lidarr-amd` but for some reason the old setup didn't work.

Anyway, it's working great now. Thanks for all your help and I hope I didn't waste too much of your time.

**Comment by RandomNinjaAtk** [comment] 2020-08-06 12:39
Yeah, a big sticking point is the volumes and variable have to align correctly for it to work correctly. It's a basic issue, but problematic for most to understand. That's why the lidarr/radarr/sonarr apps have remote path mapping features (translate), but that cannot be used in this case.

However, you did identify an issue with permissions, and this did resolve that. Other than that, just config issue on your side. Hopefully this issue will help anyone else whom gets stuck...

**Closed by RandomNinjaAtk** 2020-08-06 12:39 UTC
Labels: bug

**Comment by KINGLIFER** [comment] 2022-03-19 00:29
> `SCRIPT VERSION 1.0.01` when I made my previous post.
> 
> What I think got it all working was I changed the volume mappings and the AMD `DOWNLOAD` env var;
> 
> Old volume mapping: `- $DATA/direct/lidarr-amd:/downloads` New volume mapping: `- $DATA:/data`
> 
> Old DOWNLOAD var: `/downloads` New DOWNLOAD var: `/data/direct/lidarr-amd`
> 
> Old and new all point to the same place `/data/direct/lidarr-amd` but for some reason the old setup didn't work.
> 
> Anyway, it's working great now. Thanks for all your help and I hope I didn't waste too much of your time.

This response is so confusing to me lol. Gosh... I have the same problem (just recently) and not sure how you fixed your problem. If anyone has any idea what this person was saying I would appreciate it.
